sudo: required

language: node_js

node_js:
  - 4
  - 6
  - 8

services:
  - docker

before_script:
  - docker run -d -p 27017:27017 mongo:3
  - docker ps -a

script:
  - npm run lint
  - MONGODB_URL=mongodb://localhost/connect-mongo-test npm run cover
  - npm install mongodb@1.x
  - MONGODB_URL=mongodb://localhost/connect-mongo-test npm run test

after_script:
  - npm install coveralls && cat ./coverage/lcov.info | coveralls
